---
- hosts: all
  become_method: sudo
  vars:
      user: vagrant
      home: /home/{{ user }}

  roles:
      - { role: common, tags: common }
      - { role: webtier, tags: webtier }
      - { role: dbtier, tags: dbtier }
