---
- name: Install Composer
  become: yes
  shell: >
    which composer || (
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&
    sudo php composer-setup.php --install-dir=/usr/bin --filename=composer &&
    php -r "unlink('composer-setup.php');")
