---
- include_vars: php.yml
- name: Install php-fpm
  become: yes
  apt:  pkg=php-fpm state=latest

- name: Install php-cli
  become: yes
  apt:  pkg=php-cli state=latest

# PHP Packages
- name: Install php packages
  become: yes
  apt:  pkg={{ item }} state=latest
  with_items: "{{ php_packages }}"
  notify: restart php-fpm
